app:
    service_name: transaction_service
    port: 8082

db:
    host: localhost
    user: username
    password: password
    name: transaction_service
    port: 5432

customer_service:
    service_name: customer_service
    port: 8081
