version: '3.8'

services:
    customer-db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=customer_service
        ports:
            - '5431:5432'
        volumes:
            - customer-db-data:/var/lib/postgresql/data
        networks:
            - my-network

    transaction-db:
        image: postgres:latest
        environment:
            - POSTGRES_USER=username
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=transaction_service
        ports:
            - '5432:5432'
        volumes:
            - transaction-db-data:/var/lib/postgresql/data
        networks:
            - my-network

    api:
        build:
            context: ./api_gateway
            dockerfile: deployments/Dockerfile
        ports:
            - '8080:8080'
        depends_on:
            - customer-service
            - transaction-service
        networks:
            - my-network

    customer-service:
        build:
            context: ./customer_service
            dockerfile: deployments/Dockerfile
        ports:
            - '8081:8081'
        depends_on:
            - customer-db
        networks:
            - my-network

    transaction-service:
        build:
            context: ./transaction-service
            dockerfile: deployments/Dockerfile
        ports:
            - '8082:8082'
        depends_on:
            - transaction-db
        networks:
            - my-network

networks:
    my-network:

volumes:
    customer-db-data:
    transaction-db-data:
