version: '3.8'

services:
    mysql:
        image: mysql:latest
        container_name: db-mysql
        environment:
            MYSQL_ROOT_PASSWORD: root-password
            MYSQL_DATABASE: kreditplus
            MYSQL_USER: username
            MYSQL_PASSWORD: password
        ports:
            - '3306:3306'
        volumes:
            - mysql-data:/var/lib/mysql
            - ./my-custom.cnf:/etc/mysql/conf.d/custom.cnf
        networks:
            - my-network

volumes:
    mysql-data:

networks:
    my-network:
